var dataAmazing = {
  "fechaActual": "2022-01-01",
  "eventos": [
    {
      "id": 1,
      "image": "Feria de comidas7.jpg",
      "name": "Fiesta de las colectividades",
      "date": "2021-12-12",
      "description": "Disfruta de tus platos favoritos, de los diferentes países, en un evento único para toda la familia",
      "category": "Feria de Comida",
      "place": "Salón A",
      "capacity": 45000,
      "assistance": 42756,
      "price": 5,
      "info":"Más de 50 culturas estarán presentes en la Fiesta de Colectividades, el encuentro será desde las 12:00 hasta las 18:00 horas. Será una jornada para vivir la multiculturalidad a través de la gastronomía, artesanía, música y danzas típicas de las comunidades extranjeras. Este evento busca alentar el reconocimiento y la apreciación de la diversidad cultural aportada por las colectividades dentro de la identidad de la Ciudad. En los stands podrás degustar una gran variedad de platos típicos y en los puestos artesanales podrás disfrutar de: exhibición de vestimentas tradicionales, fotos y videos acerca de la historia de sus comunidades.",
    },

    {
      "id": 2,
      "image": "Salida al museo5.jpg",
      "name": "Parque Jurásico",
      "date": "2021-11-02",
      "description": "Vamos al museo de paleontología a hacer un recorrido increíble para conocer los más grandes dinosaurios",
      "category": "Salida al museo",
      "place": "Campo",
      "capacity": 82000,
      "assistance": 65892,
      "price": 15,
      "info":"Esta salida propone un recorrido por la historia de la vida en el planeta, con la exhibición de material paleontológico y arqueológico rescatado, en esta visita podrás conocer a los dinosaurios argentinos que habitaron nuestro territorio hace millones de años. La exhibición alberga más de 30 especies  de dinosaurios terrestres y marinos.",
    },
    {
      "id": 3,
      "image": "Fiesta de disfraces1.jpg",
      "name": "Noche de Halloween",
      "date": "2022-02-12",
      "description": "Ven con tu personaje disfraz más aterrador para ganar increíbles premios",
      "category": "Fiesta de Disfraces",
      "place": "Salón C",
      "capacity": 12000,
      "estimate": 9000,
      "price": 12,
      "info": "La ciudad se viste de miedo, terror y fantasmas para festejar Halloween. Con Disfraces, música y mucha diversión además de la gran oferta de tragos y bebidas, será el premio al mejor disfraz de la noche, por lo que la vestimenta especial será obligatoria. Las puertas se abrirán a partir de la medianoche y ya puedes adquirir tus entradas anticipadas."
    },
    {
      "id": 4,
      "image": "Concierto de musica1.jpg",
      "name": "Metallica in concert",
      "date": "2022-01-22",
      "description": "Unico recital de la banda más emblemática ",
      "category": "Concierto de Música",
      "place": "Salón A",
      "capacity": 138000,
      "estimate": 138000,
      "price": 150,
      "info":"Metallica, la legendaria banda liderada por James Hetfield, ha reprogramado su show en el Campo Argentino de Polo con Greta Van Fleet como banda invitada. La banda se encuentra celebrando el 30 aniversario de The Black Album, uno de sus discos de mayor éxito con una gira por 12 países y 48 conciertos próximos. Después de dos años de espera, finalmente Metallica reconfirma fechas y vuelve a Latinoamérica, tendremos una única fecha de presentación. No te pierdas la oportunidad de ver a tu banda favorita en vivo!",
      },
    {
      "id": 5,
      "image": "Maraton3.jpg",
      "name": "10K por la vida",
      "date": "2021-03-01",
      "description": "Ven y haz ejercicio, mejora tu salud y tu estilo de vida",
      "category": "Carrera",
      "place": "Campo de Futból",
      "capacity": 30000,
      "assistance": 25698,
      "price": 3,
      "info":"Tenemos claro que correr puede cambiar tu día, tu vida e incluso el mundo. Por eso queremos que cada vez más personas se animen a compartir su pasión por correr. En esta nueva edición de los tenemos un desafío de 10k. ¡No puedes perderte esta experiencia!"
    },
    {
      "id": 6,
      "image": "Libros7.jpg",
      "name": "Feria del libro Escolar",
      "date": "2021-10-15",
      "description": "Trae tu libro escolar que ya no usas y lleva el que necesites",
      "category": "Intercambio de Libros",
      "place": "Salón D1",
      "capacity": 150000,
      "assistance": 123286,
      "price": 1
    },
    {
      "id": 7,
      "image": "Cine7.jpg",
      "name": "Avengers",
      "date": "2022-10-15",
      "description": "Premier en 3d de Avengers de Marvel el inicio de una saga epica con tus mejores superheroes",
      "category": "Vamos al Cine",
      "place": "Salón D1",
      "capacity": 9000,
      "estimate": 9000,
      "price": 250
    }
  ]
}